# Generated by Django 2.2 on 2020-03-29 08:55

from django.db import migrations
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraper_tool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapdata',
            name='url',
        ),
        migrations.AddField(
            model_name='scrapdata',
            name='data',
            field=jsonfield.fields.JSONField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
