# Generated by Django 2.2 on 2020-03-29 11:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraper_tool', '0002_auto_20200329_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapdata',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapdata',
            name='phone',
            field=models.TextField(default=datetime.datetime(2020, 3, 29, 11, 34, 34, 4851, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
