# Generated by Django 2.2 on 2020-03-29 13:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraper_tool', '0003_auto_20200329_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapdata',
            old_name='data',
            new_name='links',
        ),
        migrations.AddField(
            model_name='scrapdata',
            name='main_url',
            field=models.CharField(default=datetime.datetime(2020, 3, 29, 13, 42, 17, 422870, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scrapdata',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
