# Generated by Django 2.2 on 2020-03-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraper_tool', '0004_auto_20200329_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapdata',
            name='links',
            field=models.TextField(),
        ),
    ]
