# Generated by Django 2.2 on 2020-03-29 13:49

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraper_tool', '0005_auto_20200329_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapdata',
            name='links',
            field=jsonfield.fields.JSONField(),
        ),
    ]
